/**
 * Reel-plan schema. Single source of truth for any video the system can produce.
 *
 * A plan is a JSON document describing:
 *   - meta (title, language, voice)
 *   - a list of scenes (discriminated union, one entry per scene type)
 *   - per-scene narration (TTS'd separately and sequenced)
 *   - an optional explicit caption track (auto-derived from narration if omitted)
 *
 * Generated by Claude (`generator/plan-with-claude.ts`) or hand-edited.
 * Validated everywhere with Zod so a malformed plan fails fast.
 */
import { z } from "zod";

/* ─── Shared primitives ─────────────────────────────────────────────────── */

export const Vec2 = z.object({ x: z.number(), y: z.number() });
export type Vec2 = z.infer<typeof Vec2>;

export const CursorWaypoint = z.object({
  /** Seconds from the start of the *scene* this waypoint belongs to */
  at: z.number().nonnegative(),
  x: z.number(),
  y: z.number(),
  control: Vec2.optional(),
  click: z.boolean().optional(),
});
export type CursorWaypoint = z.infer<typeof CursorWaypoint>;

export const Caption = z.object({
  text: z.string().min(1),
  /** Seconds from start of the *whole video* */
  at: z.number().nonnegative(),
  /** Seconds the caption stays on screen */
  hold: z.number().positive().default(1.0),
  /** 0..1080 (centred horizontally if omitted) */
  x: z.number().optional(),
  /** 0..1920 (vertical position) */
  y: z.number().optional(),
  rotation: z.number().default(0),
  variant: z.enum(["primary", "secondary"]).default("primary"),
});
export type Caption = z.infer<typeof Caption>;

/* ─── Scene-specific schemas ────────────────────────────────────────────── */

const SceneBase = z.object({
  id: z.string().min(1),
  durationSeconds: z.number().positive(),
  /** Narration spoken during this scene. Concatenated across scenes for TTS. */
  narration: z.string().default(""),
});

export const TitleScene = SceneBase.extend({
  type: z.literal("title"),
  title: z.string(),
  subtitle: z.string().optional(),
  /** Hero illustration choice */
  illustration: z.enum(["desktop", "none"]).default("desktop"),
  showRings: z.boolean().default(true),
});
export type TitleScene = z.infer<typeof TitleScene>;

export const BrowserScene = SceneBase.extend({
  type: z.literal("browser"),
  /** Display URL in the chrome bar */
  url: z.string(),
  /** Either "google" (renders MockGoogleSearch with the given query),
   *  "vscode" (renders MockVSCodeWebsite),
   *  or "recording" (plays a Playwright-recorded video from /recordings/<file>) */
  content: z.discriminatedUnion("kind", [
    z.object({ kind: z.literal("google"), query: z.string() }),
    z.object({ kind: z.literal("vscode") }),
    z.object({ kind: z.literal("recording"), file: z.string() }),
    z.object({
      kind: z.literal("custom"),
      /** Any HTML to render inside the browser viewport. */
      html: z.string(),
    }),
  ]),
  /** Seconds 0..durationSeconds — controls page scroll over time */
  scroll: z
    .array(z.object({ at: z.number(), y: z.number() }))
    .default([{ at: 0, y: 0 }]),
  cursorPath: z.array(CursorWaypoint).default([]),
});
export type BrowserScene = z.infer<typeof BrowserScene>;

export const TerminalScene = SceneBase.extend({
  type: z.literal("terminal"),
  user: z.string().default("user"),
  host: z.string().default("Mac"),
  lines: z.array(
    z.object({
      /** Seconds from scene start */
      at: z.number().nonnegative(),
      /** Seconds the typing animation takes */
      typeFor: z.number().positive().default(1.0),
      text: z.string(),
      prompt: z.boolean().default(false),
      color: z.string().optional(),
    }),
  ),
});
export type TerminalScene = z.infer<typeof TerminalScene>;

export const DesktopScene = SceneBase.extend({
  type: z.literal("desktop"),
  /** Show the macOS right-click context menu? */
  contextMenu: z
    .object({
      at: Vec2.default({ x: 510, y: 1210 }),
      /** Frame-style seconds to wait before the menu appears */
      openAt: z.number().nonnegative().default(0.7),
      /** Index of menu item to highlight (after opening) */
      highlightIndex: z.number().int().nullable().default(null),
      /** Seconds at which to highlight that item */
      highlightAt: z.number().nonnegative().optional(),
    })
    .optional(),
  cursorPath: z.array(CursorWaypoint).default([]),
});
export type DesktopScene = z.infer<typeof DesktopScene>;

export const CodeScene = SceneBase.extend({
  type: z.literal("code"),
  language: z.string().default("ts"),
  code: z.string(),
  /** Filename shown in the tab */
  filename: z.string().default("snippet.ts"),
  /** Highlight a line (1-indexed) at a given second */
  highlights: z
    .array(z.object({ at: z.number(), line: z.number().int().positive() }))
    .default([]),
});
export type CodeScene = z.infer<typeof CodeScene>;

export const OutroScene = SceneBase.extend({
  type: z.literal("outro"),
  bigText: z.string().default("Done."),
  smallText: z.string().default("Follow for more"),
});
export type OutroScene = z.infer<typeof OutroScene>;

export const Scene = z.discriminatedUnion("type", [
  TitleScene,
  BrowserScene,
  TerminalScene,
  DesktopScene,
  CodeScene,
  OutroScene,
]);
export type Scene = z.infer<typeof Scene>;

/* ─── Top-level plan ────────────────────────────────────────────────────── */

export const ReelPlan = z.object({
  meta: z.object({
    /** Stable id used for filenames, eg "setup-claude-code" */
    id: z.string().min(1),
    title: z.string(),
    subtitle: z.string().optional(),
    language: z.enum(["en", "he"]).default("en"),
    /** Provider voice id (eg ElevenLabs voice id) */
    voiceId: z.string().optional(),
    fps: z.number().int().positive().default(30),
  }),
  scenes: z.array(Scene).min(1),
  /** Optional manual caption track. If empty, captions are auto-generated. */
  captions: z.array(Caption).default([]),
});
export type ReelPlan = z.infer<typeof ReelPlan>;

/** Helpers shared by render code: convert seconds to frames at plan fps. */
export const sceneDurationFrames = (s: Scene, fps: number) =>
  Math.round(s.durationSeconds * fps);

export const totalDurationFrames = (plan: ReelPlan) =>
  plan.scenes.reduce(
    (acc, s) => acc + sceneDurationFrames(s, plan.meta.fps),
    0,
  );

export const sceneStartFrame = (
  plan: ReelPlan,
  index: number,
): number => {
  let acc = 0;
  for (let i = 0; i < index; i++) {
    acc += sceneDurationFrames(plan.scenes[i]!, plan.meta.fps);
  }
  return acc;
};
